name: junction_fortum
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.21
  - pandas>=1.3
  - scikit-learn>=1.0
  - xgboost>=1.6
  - lightgbm
  - matplotlib
  - seaborn
  - jupyterlab
  - openpyxl
  - mlflow
  - joblib
  - pyyaml
  - requests
  - pytest
  - statsmodels
  - pip:
    - optuna
    - category-encoders
    - wittgenstein
